### ISSUE TITLE
CRUD - read and searchbar

### ISSUE THREAD

**Issue by Japy88** [brunosantoshx/treinamento-php-activerecord#2]
Boas Bruno,
Desde já deixa-me dizer que o programa de cadastramento está brutal, desde as tuas explicações ao próprio conteúdo.
No entanto, faz um ano desde que fizeste a rubrica do php-activerecord e a estrutura não é a mesma. Consegui introduzir dados no phpmyadmin através de formulário, mas não sei como visualizá-los nem como associar à barra de pesquisa.
Abraço e continua com o bom trabalho.

**Comment by brunosantoshx** [comment]
Olá @Japy88, como vai?

Obrigado! Valeu pelo feedback

**Sobre sua dúvida:**
Nada vai mudar se trabalhar diretamente com o PHP Activerecord ou através da implementação no HXPHP. Você sempre terá um `model` e é através dele que você executará o `CRUD`.

Para uma barra de pesquisa realmente é necessária uma adaptação:

```php
	//Exemplo de Produtos

	//app/models/Product.php

	public static function todosProdutos()
	{
		return self::all();
	}

	public static function buscarProduto($stringPesquisa)
	{
		// Uso do LIKE %...%
		$search = self::all([
			'conditions' => [
				'name LIKE ? OR description LIKE ?',
				'%' . $stringPesquisa . '%',
				'%' . $stringPesquisa . '%'
			]
		]);

		return $search;
	}
```

**Comment by brunosantoshx** [comment]
E para exibir estes dados na view:

+ No `controller` você vai resgatar os dados do `model` e enviar para a `view`:
```php
$search_results = Product::buscarProduto($this->request->get('search'));
$this->view->setVar('search_results', $search_results);
```
- Na `view` você vai percorrer e exibir os dados:
```php
if ($view_search_results) :
  foreach ($view_search_results as $product) :
    echo $product->title;
  endforeach;
endif;
```

**Comment by Japy88** [comment]
Boas Bruno,


Tentei fazer o que me disseste mas aparece um erro:


Fatal error: Uncaught exception 'ActiveRecord\ActiveRecordException' with message 'Call to undefined method: procurarCliente' in C:\xampp\htdocs\Iurisdb\vendor\php-activerecord\php-activerecord\lib\Model.php:1401 Stack trace: #0 C:\xampp\htdocs\Iurisdb\app\controllers\VisualizarController.php(43): ActiveRecord\Model::__callStatic('procurarCliente', Array) #1 C:\xampp\htdocs\Iurisdb\app\controllers\VisualizarController.php(43): Client::procurarCliente(NULL) #2 [internal function]: VisualizarController->lerAction() #3 C:\xampp\htdocs\Iurisdb\src\HXPHP\System\App.php(103): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\Iurisdb\index.php(36): HXPHP\System\App->run() #5 {main} thrown in C:\xampp\htdocs\Iurisdb\vendor\php-activerecord\php-activerecord\lib\Model.php on line 1401.


Criei este model:


<?php

class Require extends \HXPHP\System\Model
{
        public static function todosClientes()
    {
        return self::all();
    }

    public static function procurarCliente($stringPesquisa)
    {
        // Uso do LIKE %...%
        $search = self::all([
            'conditions' => [
                'name LIKE ? OR description LIKE ?',
                '%' . $stringPesquisa . '%',
                '%' . $stringPesquisa . '%'
            ]
        ]);

        return $search;
    }
}


// Controller


<?php

class VisualizarController extends \HXPHP\System\Controller
{
    public function __construct($configs)
    {
        parent::__construct($configs);

        $this->load(
            'Services\Auth',
            $configs->auth->after_login,
            $configs->auth->after_logout,
            true
        );

        $this->auth->redirectCheck();

        $this->load(
            'Helpers\Menu',
            $this->request,
            $this->configs,
            $this->auth->getUserRole()
        );

        $user_id = $this->auth->getUserId();

        $this->view->setTitle('Iurisdb - Home')
                    ->setVar('user', User::find($user_id));
    }

    public function bloqueadaAction()
    {
        $this->auth->roleCheck([
            'administrator',
            'user'
        ]);
    }

    public function lerAction()
    {
        $this->view->setFile('index');

        $search_results = Client::procurarCliente($this->request->get('search'));
        $this->view->setVar('search_results', $search_results);

        if ($view_search_results) :
          foreach ($view_search_results as $product) :
        echo $product->title;
          endforeach;
        endif;
      }
}


// View

<head>
<?php
    echo isset($this->menu) ? $this->menu->getMenu() : '';
?>
</head>


<script>
function showResult(str) {
  if (str.length==0) {
    document.getElementById("livesearch").innerHTML="";
    document.getElementById("livesearch").style.border="0px";
    return;
  }
  if (window.XMLHttpRequest) {
    // code for IE7+, Firefox, Chrome, Opera, Safari
    xmlhttp=new XMLHttpRequest();
  } else {  // code for IE6, IE5
    xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
  }
  xmlhttp.onreadystatechange=function() {
    if (xmlhttp.readyState==4 && xmlhttp.status==200) {
      document.getElementById("livesearch").innerHTML=xmlhttp.responseText;
      document.getElementById("livesearch").style.border="1px solid #A5ACB2";
    }
  }
  xmlhttp.open("GET","livesearch.php?q="+str,true);
  xmlhttp.send();
}
</script>
</head>
<body>

<form>
<input type="text" class="form-control" onkeyup="showResult(this.value)">
<div id="livesearch"></div>
</form>


Não faço ideia de qual possa ser o erro... E já agora, o método GET pode ser criado no mesmo ficheiro que o POST? É que o objetivo é mostrar uma ficha de clientes e queria saber se o model de ligação à base de dados pode ser o mesmo para o POST e GET ou se preciso criar dois independentes.

Abraço



________________________________
De: Bruno Campos Santos <notifications@github.com>
Enviado: terça-feira, 16 de agosto de 2016 21:20
Para: brunosantoshx/treinamento-php-activerecord
Cc: Japy88; Mention
Assunto: Re: [brunosantoshx/treinamento-php-activerecord] CRUD - read and searchbar (#2)


E para exibir estes dados na view:

  *   No controller você vai resgatar os dados do model e enviar para a view:

$search_results = Product::buscarProduto($this->request->get('search'));
$this->view->setVar('search_results', $search_results);

  *   Na view você vai percorrer e exibir os dados:

if ($view_search_results) :
  foreach ($view_search_results as $product) :
    echo $product->title;
  endforeach;
endif;

-

**Comment by brunosantoshx** [comment]
Olá @Japy88, como vai?

Veja seu código do model: 
```php
class Require extends \HXPHP\System\Model
```

Você nomeou o model de `Require` e depois invocou o método com o nome `Client`. O erro reportado foi: **'Call to undefined method: procurarCliente'**, isto é, não existe o método chamado porque o nome do model que tem o método é diferente.

Abração!

**Comment by Japy88** [comment]
Boas Bruno,

Desde já agradeço a imensa ajuda, mas não tou dando conta do recado..

Ainda não consigo ver os dados da base de dados, aparece-me agora o erro:

 Notice: Undefined variable: view_search_results in C:\xampp\htdocs\Iurisdb\app\controllers\VerController.php on line 46.

//model
<?php

class Client extends \HXPHP\System\Model
{
	static $validates_presence_of = [
		[
			'name',
			'message' => 'O nome é um campo obrigatório.'
		],
		[
			'surname',
			'message' => 'O apelido é um campo obrigatório.'
		],
		[
			'mobilephone',
			'message' => 'O nº de telemóvel é um campo obrigatório.'
		],
	];

	public static function criar(array $post)
	{
		return self::create($post);
	}

	public static function todosClientes()
    {
        return self::all();
    }

    public static function procurarCliente($stringPesquisa)
    {
        // Uso do LIKE %...%
        $search = self::all([
            'conditions' => [
                'name LIKE ? OR description LIKE ?',
                '%' . $stringPesquisa . '%',
                '%' . $stringPesquisa . '%'
            ]
        ]);

        return $search;
    }
}


//controller

<?php

class VerController extends \HXPHP\System\Controller
{
	public function __construct($configs)
	{
		parent::__construct($configs);

		$this->load(
			'Services\Auth',
			$configs->auth->after_login,
			$configs->auth->after_logout,
			true
		);

		$this->auth->redirectCheck();

		$this->load(
			'Helpers\Menu',
			$this->request,
			$this->configs,
			$this->auth->getUserRole()
		);

		$user_id = $this->auth->getUserId();

		$this->view->setTitle('Iurisdb - Home')
					->setVar('user', User::find($user_id));
	}

	public function bloqueadaAction()
	{
		$this->auth->roleCheck([
			'administrator',
			'user'
		]);
	}

	public function todosClientesAction()
	{
		$this->view->setFile('index');

		$search_results = Client::todosClientes($this->request->get('search'));
		$this->view->setVar('search_results', $search_results);

		if ($view_search_results) :
		  foreach ($view_search_results as $client) :
		    echo $client->name;
		  endforeach;
		endif;
	}
}


//view

<head>
<?php 
    echo isset($this->menu) ? $this->menu->getMenu() : '';
?>
</head>
<body>
	<form action="<?php echo BASE; ?>ver/todosclientes/" method="GET">
<input id="search" type="text" class="col-md-offset-0 form-control" placeholder="Procurar">
<input id="submit" type="submit" class="btn btn-success" value="Pesquisar">
</form><br>
</body>
</head>

Abraço

**Comment by brunosantoshx** [comment]
Olá @Japy88, como vai?

A variável `$view_search_results` não existe no controller, isto é, a extração só é disponível para a camada da visualização. Você só teria que alterar para `$search_results` que é o nome da variável que você definiu no controller.

Os erros do PHP são muito sugestíveis e interpretar cada tipo de erro é fundamental para crescer como programador. A própria mensagem do erro já tinha te informado o que apenas repeti acima em pt-br. Estude sobre erros e exceptions para conseguir corrigir todos os problemas que surgirem porque isso é parte da rotina.

Forte abraço e sucesso sempre!
